//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Absence
    {
        public A_Absence()
        {
            this.WorkerId = 0;
            this.Type = "L";
        }
    
        public int Id { get; private set; }
        public int WorkerId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Type { get; set; }
    
        public virtual A_Worker A_Worker { get; set; }
    }
}
