//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_DictionaryRoom
    {
        public A_DictionaryRoom()
        {
            this.ClinicId = 0;
            this.IsDeleted = false;
            this.New = 0;
        }
    
        public int Id { get; private set; }
        public string Number { get; set; }
        public int ClinicId { get; set; }
        public bool IsDeleted { get; set; }
        public int New { get; set; }
    }
}
