//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_User
    {
        public A_User()
        {
            this.WorkerId = 0;
        }
    
        public int Id { get; private set; }
        public int WorkerId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime Active { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
    }
}
