//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Worker
    {
        public A_Worker()
        {
            this.Gender = false;
            this.JobTitle = 0;
            this.Specialization = 0;
        }
    
        public int Id { get; private set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public bool Gender { get; set; }
        public long Pesel { get; set; }
        public int JobTitle { get; set; }
        public int Specialization { get; set; }
        public string Street { get; set; }
        public string BuildingNumber { get; set; }
        public string Apartment { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Post { get; set; }
    }
}
