//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DictionaryClinic
    {
        public M_DictionaryClinic()
        {
            this.IsNfzContracted = true;
            this.IsDeleted = false;
            this.New = 0;
            this.A_DictionaryRooms = new HashSet<A_DictionaryRoom>();
        }
    
        public int Id { get; private set; }
        public string Name { get; set; }
        public bool IsNfzContracted { get; set; }
        public bool IsDeleted { get; set; }
        public int New { get; set; }
    
        public virtual ICollection<A_DictionaryRoom> A_DictionaryRooms { get; set; }
    }
}
