//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_L4Disease
    {
        public M_L4Disease()
        {
            this.Disease = 0;
        }
    
        public int VisitId { get; set; }
        public int Disease { get; set; }
        public string L4Number { get; set; }
    }
}
