//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MedicalTreatment
    {
        public M_MedicalTreatment()
        {
            this.VisitId = 0;
            this.DoctorId = 0;
            this.PatientId = 0;
            this.DoerId = 0;
            this.MedicalTreatment = 0;
            this.IsPrivate = false;
        }
    
        public int Id { get; private set; }
        public int VisitId { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public int DoerId { get; set; }
        public System.DateTime Ordered { get; set; }
        public Nullable<System.DateTime> DateOfExecution { get; set; }
        public Nullable<System.DateTime> Executed { get; set; }
        public byte State { get; set; }
        public int MedicalTreatment { get; set; }
        public bool IsPrivate { get; set; }
        public string Description { get; set; }
        public string Result { get; set; }
        public string Comments { get; set; }
    }
}
