//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MedicalTreatment
    {
        public M_MedicalTreatment()
        {
            this.VisitId = 0;
            this.DoctorId = 0;
            this.PatientId = 0;
            this.DoerId = 0;
            this.VerifierId = 0;
            this.EditorId = 0;
            this.State = 0;
            this.MedicalTreatment = 0;
            this.IsPrivate = false;
        }
    
        public int Id { get; private set; }
        public int VisitId { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public int DoerId { get; set; }
        public int VerifierId { get; set; }
        public int EditorId { get; set; }
        public System.DateTime Ordered { get; set; }
        public Nullable<System.DateTime> DateOfExecution { get; set; }
        public Nullable<System.DateTime> StartOfExecution { get; set; }
        public Nullable<System.DateTime> EndOfExecution { get; set; }
        public Nullable<System.DateTime> Verified { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
        public byte State { get; set; }
        public int MedicalTreatment { get; set; }
        public bool IsPrivate { get; set; }
        public string Description { get; set; }
        public string Result { get; set; }
        public string Comments { get; set; }
    
        public virtual M_Visit M_Visit { get; set; }
        public virtual A_Worker A_Worker_DoctorId { get; set; }
        public virtual M_Patient M_Patient { get; set; }
        public virtual A_Worker A_Worker_DoerId { get; set; }
        public virtual M_DictionaryMedicalTreatment M_DictionaryMedicalTreatment { get; set; }
        public virtual A_Worker A_Worker_VerifierId { get; set; }
        public virtual A_Worker A_Worker_EditorId { get; set; }
    }
}
