//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Patient
    {
        public M_Patient()
        {
            this.Gender = false;
            this.IsInsured = true;
            this.M_Visits = new HashSet<M_Visit>();
            this.M_MedicalTreatments = new HashSet<M_MedicalTreatment>();
        }
    
        public int Id { get; private set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public bool Gender { get; set; }
        public long Pesel { get; set; }
        public string Street { get; set; }
        public string BuildingNumber { get; set; }
        public string Apartment { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Post { get; set; }
        public bool IsInsured { get; set; }
        public string NfzBranch { get; set; }
    
        public virtual ICollection<M_Visit> M_Visits { get; set; }
        public virtual ICollection<M_MedicalTreatment> M_MedicalTreatments { get; set; }
    }
}
