//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Prescription
    {
        public M_Prescription()
        {
            this.VisitId = 0;
        }
    
        public int Id { get; private set; }
        public int VisitId { get; set; }
        public string Number { get; set; }
    }
}
