//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Visit
    {
        public M_Visit()
        {
            this.RegistrarId = 0;
            this.DoctorId = 0;
            this.PatientId = 0;
            this.State = 0;
        }
    
        public int Id { get; private set; }
        public int RegistrarId { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public System.DateTime Registered { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public byte State { get; set; }
        public string Description { get; set; }
        public string Diagnosis { get; set; }
    }
}
