//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Visit
    {
        public M_Visit()
        {
            this.RegistrarId = 0;
            this.DoctorId = 0;
            this.PatientId = 0;
            this.State = 0;
            this.M_MedicalTreatments = new HashSet<M_MedicalTreatment>();
            this.M_Prescriptions = new HashSet<M_Prescription>();
        }
    
        public int Id { get; private set; }
        public int RegistrarId { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public System.DateTime Registered { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Ended { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
        public byte State { get; set; }
        public string Description { get; set; }
        public string Diagnosis { get; set; }
    
        public virtual A_Worker A_Worker_RegistrarId { get; set; }
        public virtual A_Worker A_Worker_DoctorId { get; set; }
        public virtual M_Patient M_Patient { get; set; }
        public virtual ICollection<M_MedicalTreatment> M_MedicalTreatments { get; set; }
        public virtual M_L4Disease M_L4Disease { get; set; }
        public virtual ICollection<M_Prescription> M_Prescriptions { get; set; }
    }
}
