//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalCenterDBContainer : DbContext
    {
        public MedicalCenterDBContainer()
            : base("name=MedicalCenterDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal DbSet<A_Calendar> A_Calendars { get; set; }
        public DbSet<A_Absence> A_Absences { get; set; }
        public DbSet<A_User> A_Users { get; set; }
        public DbSet<A_Schedule> A_Schedules { get; set; }
        public DbSet<A_DictionaryJobTitle> A_DictionaryJobTitles { get; set; }
        public DbSet<A_DictionarySpecialization> A_DictionarySpecializations { get; set; }
    }
}
