//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalCenterDBContainer : DbContext
    {
        public MedicalCenterDBContainer()
            : base("name=MedicalCenterDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<A_Calendar> A_Calendars { get; set; }
        public DbSet<A_Absence> A_Absences { get; set; }
        public DbSet<A_User> A_Users { get; set; }
        public DbSet<A_Schedule> A_Schedules { get; set; }
        public DbSet<A_DictionaryJobTitle> A_DictionaryJobTitles { get; set; }
        public DbSet<A_DictionarySpecialization> A_DictionarySpecializations { get; set; }
        public DbSet<A_Worker> A_Workers { get; set; }
        public DbSet<M_Visit> M_Visits { get; set; }
        public DbSet<M_MedicalTreatment> M_MedicalTreatments { get; set; }
        public DbSet<M_Patient> M_Patients { get; set; }
        public DbSet<M_Prescription> M_Prescriptions { get; set; }
        public DbSet<M_L4Disease> M_L4Diseases { get; set; }
        public DbSet<M_DictionaryDisease> M_DictionaryDiseases { get; set; }
        public DbSet<M_DictionaryMedicalTreatment> M_DictionaryMedicalTreatments { get; set; }
        public DbSet<A_WorkersRoom> A_WorkersRooms { get; set; }
        public DbSet<A_DictionaryRoom> A_DictionaryRooms { get; set; }
        public DbSet<M_DictionaryClinic> M_DictionaryClinics { get; set; }
    }
}
